namespace GmutagenEngine.Requests.Http.Headers
{
    public static class HttpHeaderExtensions
    {
        public static string AsString(this HttpHeaderType headerType) => headerType switch
        {
            HttpHeaderType.CacheControl => "Cache-Control",
            HttpHeaderType.Connection => "Connection",
            HttpHeaderType.Date => "Date",
            HttpHeaderType.Pragma => "Pragma",
            HttpHeaderType.Trailer => "Trailer",
            HttpHeaderType.TransferEncoding => "Transfer-Encoding",
            HttpHeaderType.Upgrade => "Upgrade",
            HttpHeaderType.Via => "Via",
            HttpHeaderType.Warning => "Warning",

            HttpHeaderType.Accept => "Accept",
            HttpHeaderType.AcceptCharset => "Accept-Charset",
            HttpHeaderType.AcceptEncoding => "Accept-Encoding",
            HttpHeaderType.AcceptLanguage => "Accept-Language",
            HttpHeaderType.Authorization => "Authorization",
            HttpHeaderType.Cookie => "Cookie",
            HttpHeaderType.Expect => "Expect",
            HttpHeaderType.From => "From",
            HttpHeaderType.Host => "Host",
            HttpHeaderType.IfMatch => "If-Match",
            HttpHeaderType.IfModifiedSince => "If-Modified-Since",
            HttpHeaderType.IfNoneMatch => "If-None-Match",
            HttpHeaderType.IfRange => "If-Range",
            HttpHeaderType.IfUnmodifiedSince => "If-Unmodified-Since",
            HttpHeaderType.MaxForwards => "Max-Forwards",
            HttpHeaderType.ProxyAuthorization => "Proxy-Authorization",
            HttpHeaderType.Range => "Range",
            HttpHeaderType.Referer => "Referer",
            HttpHeaderType.TE => "TE",
            HttpHeaderType.UserAgent => "User-Agent",

            HttpHeaderType.AcceptRanges => "Accept-Ranges",
            HttpHeaderType.Age => "Age",
            HttpHeaderType.ETag => "ETag",
            HttpHeaderType.Location => "Location",
            HttpHeaderType.ProxyAuthenticate => "Proxy-Authenticate",
            HttpHeaderType.RetryAfter => "Retry-After",
            HttpHeaderType.Server => "Server",
            HttpHeaderType.Vary => "Vary",
            HttpHeaderType.WWWAuthenticate => "WWW-Authenticate",

            HttpHeaderType.Allow => "Allow",
            HttpHeaderType.ContentEncoding => "Content-Encoding",
            HttpHeaderType.ContentLanguage => "Content-Language",
            HttpHeaderType.ContentLength => "Content-Length",
            HttpHeaderType.ContentLocation => "Content-Location",
            HttpHeaderType.ContentMD5 => "Content-MD5",
            HttpHeaderType.ContentRange => "Content-Range",
            HttpHeaderType.ContentType => "Content-Type",
            HttpHeaderType.Expires => "Expires",
            HttpHeaderType.LastModified => "Last-Modified",

            HttpHeaderType.AccessControlAllowOrigin => "Access-Control-Allow-Origin",
            HttpHeaderType.AccessControlAllowMethods => "Access-Control-Allow-Methods",
            HttpHeaderType.AccessControlAllowHeaders => "Access-Control-Allow-Headers",
            HttpHeaderType.AccessControlExposeHeaders => "Access-Control-Expose-Headers",
            HttpHeaderType.AccessControlMaxAge => "Access-Control-Max-Age",
            HttpHeaderType.AccessControlRequestHeaders => "Access-Control-Request-Headers",
            HttpHeaderType.AccessControlRequestMethod => "Access-Control-Request-Method",
            HttpHeaderType.Origin => "Origin",
            HttpHeaderType.CrossOriginOpenerPolicy => "Cross-Origin-Opener-Policy",
            HttpHeaderType.CrossOriginResourcePolicy => "Cross-Origin-Resource-Policy",
            HttpHeaderType.StrictTransportSecurity => "Strict-Transport-Security",
            HttpHeaderType.XContentTypeOptions => "X-Content-Type-Options",
            HttpHeaderType.XFrameOptions => "X-Frame-Options",
            HttpHeaderType.XXSSProtection => "X-XSS-Protection",
            HttpHeaderType.ReferrerPolicy => "Referrer-Policy",

            HttpHeaderType.AuthorizationBearer => "Authorization",
            HttpHeaderType.RequestId => "Request-Id",
            HttpHeaderType.CorrelationId => "Correlation-Id",
            HttpHeaderType.XApiKey => "X-Api-Key",
            HttpHeaderType.XRequestedWith => "X-Requested-With",
            HttpHeaderType.XForwardedFor => "X-Forwarded-For",
            HttpHeaderType.XForwardedProto => "X-Forwarded-Proto",
            HttpHeaderType.XRealIp => "X-Real-IP",
            HttpHeaderType.XPoweredBy => "X-Powered-By",
            HttpHeaderType.TraceParent => "Trace-parent",

            _ => throw new ArgumentOutOfRangeException(nameof(headerType), headerType, null)
        };
    }
}